# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?useSSL=false&serverTimezone=UTC
    username: root
    password: 121109
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
          max-file-size: 10MB
          max-request-size: 10MB

  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    username: ganlan201672@163.com
    password: NV47B34fRYJGwjZ9
    test-connection: true
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
            required: true




  data:
    redis:
      host: localhost
      port: 6379
      password: 121109

# MyBatis配置（如果使用MyBatis）
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: fun.struct.myblog.entity

# 设置文件上传大小

# 图片保存路径
app:
  remote:
    upload:
      url: https://image.struct.fun/api/index.php
      token: 0615f90398fa52492ad5776ba9884fa1

# JWT 配置
jwt:
  signingKey: U29tZVZlcnlMb25nU2VjcmV0S2V5MTIzNDU2Nzg5MDEyMw==
  expire: 3600000  # 令牌过期时间，单位为毫秒（例如：1小时）


